'use strict';
var express = require('express');
var controller = require('./thing.controller');
var router = express.Router();
router.get('/', controller.index);
router.get('/:id', controller.show);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.put('/editRoom/:id', controller.myupdate);
router.put('/editOldRoom/:id', controller.myoldupdate);
router.put('/checkout/:id', controller.checkout);
router.patch('/:id', controller.update);
router.delete('/:id', controller.destroy);
module.exports = router;
